version: "2"
services:
  node:
    container_name: dockerTaller2
    build: .
    ports:
      - "3030:3030"
      - "35729:35729"
    volumes:
      - ./app:/app
  children:
    container_name: dockerTaller4
    image: node:10.10.0-slim
    depends_on:
      - node
    command: ["curl", "http://dockerTaller2:3030/#1"]

networks:
  default:
    external:
      name: orbistrainingproject_default